# Generated by Django 5.2.6 on 2025-09-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('before_image', models.ImageField(upload_to='before/')),
                ('after_image', models.ImageField(upload_to='after/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
