# Generated by Django 5.2.6 on 2025-09-06 15:10

import portfolio.utils
import portfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='after_image',
            field=models.ImageField(upload_to=portfolio.utils.UploadToPath(folder='after'), validators=[portfolio.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='before_image',
            field=models.ImageField(upload_to=portfolio.utils.UploadToPath(folder='before'), validators=[portfolio.validators.validate_file_size]),
        ),
    ]
